### ISSUE TITLE
In instruction not supported

### ISSUE THREAD

**Issue by romain145** [NathanY3G/rp2040-pio-emulator#102]
Using the "in" instruction doesn't seem to be supported by the emulator.
The decoder does not have a ""_decode_in" method in its decoding_functions.

The following program does not generate anything:
```
program = """
loop:
    in pins, 8
    mov osr, isr
    out pins, 8
    set pins, 1
    set pins, 0
    jmp loop
"""
```

**Comment by aaronjamt** [comment]
Can you provide a complete program that demonstrates this issue? Also, when you say "does not generate anything", what does that mean? This project doesn't have the ability to handle PIO assembly in its textual form, you have to use another program or library to convert it to opcodes first. If you mean that that program doesn't generate valid opcodes, that is outside the scope of this project.

**Comment by NathanY3G** [comment]
Hi @romain145. Thanks for taking the time to report a problem. This issue might be due to the version of the library being used. The `_decode_in()` function was only added about 2 months ago by this [commit](https://github.com/NathanY3G/rp2040-pio-emulator/pull/73).  Please could you specify which version of the library you are using? One way to check this is by entering the following into your Python REPL:

```python
import pioemu
pioemu.__version__
```

If you are on the latest version but still have a problem then providing a more complete example as suggested by @aaronjamt would really help. Thanks :slightly_smiling_face:

**Comment by romain145** [comment]
I was using version 0.80 installed with pip: https://pypi.org/project/rp2040-pio-emulator/0.80.0/
Using HEAD https://github.com/NathanY3G/rp2040-pio-emulator/commit/4c5560ec980a81b7512c52bdee4e8d18c50e8376 now the code runs as expected :)
Thanks!

**Comment by NathanY3G** [comment]
Great! Thanks for letting us know @romain145. If you have any more problems, questions or ideas then please feel free to post to discussion https://github.com/NathanY3G/rp2040-pio-emulator/discussions/2. Alternatively, just create another Issue.
