### ISSUE TITLE
Automated CI build fails

### ISSUE THREAD

**Issue by NathanY3G** [NathanY3G/rp2040-pio-emulator#61]
The automated CI build fails with the following error:

```
Version 3.10.0 with arch x64 not found 
```

**Comment by aaronjamt** [comment]
https://github.com/actions/setup-python/issues/401?

**Comment by NathanY3G** [comment]
Wonderful! Thanks @aaronjamt :grin:

**Comment by aaronjamt** [comment]
Actually, I don't think that's it (the issue I linked says that Debian isn't supported but you're already using the Ubuntu runner). Check this list and see if there's a newer minor version (3.10.x) since I believe they remove older ones regularly: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by aaronjamt** [comment]
Might also want to add Python 3.11 to the CI workflow

**Comment by aaronjamt** [comment]
Looks like the latest version is 3.10.10

**Comment by aaronjamt** [comment]
The pipeline doesn't appear to run on my fork so I don't know for sure but the PR i just opened (#61) should fix this (and also add 3.11 support).

**Comment by aaronjamt** [comment]
Ah, looks like you've got it. Closing my PR

**Comment by NathanY3G** [comment]
Thank you @aaronjamt for your help. I will continuing taking a look at your PRs/MRs after work. Have a great day :smile:
